In [2]:
#import PyTorch
import torch

In [2]:
# requires_grad = True -> tracks all operations on the tensor. 
x = torch.randn(3, requires_grad=True)
y = x + 2

# y was created as a result of an operation, so it has a grad_fn attribute.
# grad_fn: references a Function that has created the Tensor
print(x) # created by the user -> grad_fn is None
print(y)
print(y.grad_fn)

tensor([-2.4024, -1.2241, -0.4982], requires_grad=True)
tensor([-0.4024,  0.7759,  1.5018], grad_fn=<AddBackward0>)


In [3]:
x = torch.tensor([.0,.0,.0], requires_grad=True)

y = torch.zeros(3)
y[0]=x[0]+2*x[1]-.5*x[2]
y[1]=x[0]+1/2*x[1]+2*x[2]
y[2]=-3.5*x[0]+x[1]+2*x[2]


print(y)
print(y.shape)

v = torch.tensor([1, 2, 3], dtype=torch.float32)
y.backward(v)
print(x.grad)




tensor([0., 0., 0.], grad_fn=<CopySlices>)
torch.Size([3])
tensor([-7.5000,  6.0000,  9.5000])


In [11]:
# 1) Design model (input, output, forward pass with different layers)
# 2) Construct loss and optimizer
# 3) Training loop
#       - Forward = compute prediction and loss
#       - Backward = compute gradients
#       - Update weights

import torch
import torch.nn as nn

# Linear regression
# f = w * x 

# here : f = 2 * x

# 0) Training samples, watch the shape!
X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

n_samples, n_features = X.shape
print(f'#samples: {n_samples}, #features: {n_features}')
# 0) create a test sample
X_test = torch.tensor([8], dtype=torch.float32)

# 1) Design Model, the model has to implement the forward pass!
# Here we can use a built-in model from PyTorch
input_size = n_features
output_size = n_features

# we can call this model with samples X
model = nn.Linear(input_size, output_size)

'''
class LinearRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(LinearRegression, self).__init__()
        # define diferent layers
        self.lin = nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return self.lin(x)

model = LinearRegression(input_size, output_size)
'''

print(f'Prediction before training: f(5) = {model(X_test).item():.3f}')

# 2) Define loss and optimizer
learning_rate = 0.01
n_iters = 10000

loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# 3) Training loop
for epoch in range(n_iters):
    # predict = forward pass with our model
    y_predicted = model(X)

    # loss
    l = loss(Y, y_predicted)

    # calculate gradients = backward pass
    l.backward()

    # update weights
    optimizer.step()

    # zero the gradients after updating
    optimizer.zero_grad()

    if epoch % 1000 == 0:
        [w, b] = model.parameters() # unpack parameters
        print('epoch ', epoch+1, ': w = ', w[0][0].item(), ' loss = ', l)

print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')


#samples: 4, #features: 1
Prediction before training: f(5) = -0.536
epoch  1 : w =  0.272978812456131  loss =  tensor(33.2984, grad_fn=<MseLossBackward0>)
epoch  1001 : w =  1.9923702478408813  loss =  tensor(8.4549e-05, grad_fn=<MseLossBackward0>)
epoch  2001 : w =  1.9996192455291748  loss =  tensor(2.1068e-07, grad_fn=<MseLossBackward0>)
epoch  3001 : w =  1.9999809265136719  loss =  tensor(5.2842e-10, grad_fn=<MseLossBackward0>)
epoch  4001 : w =  1.9999972581863403  loss =  tensor(8.9813e-12, grad_fn=<MseLossBackward0>)
epoch  5001 : w =  1.9999977350234985  loss =  tensor(6.0254e-12, grad_fn=<MseLossBackward0>)
epoch  6001 : w =  1.9999977350234985  loss =  tensor(6.0254e-12, grad_fn=<MseLossBackward0>)
epoch  7001 : w =  1.9999977350234985  loss =  tensor(6.0254e-12, grad_fn=<MseLossBackward0>)
epoch  8001 : w =  1.9999977350234985  loss =  tensor(6.0254e-12, grad_fn=<MseLossBackward0>)
epoch  9001 : w =  1.9999977350234985  loss =  tensor(6.0254e-12, grad_fn=<MseLossBackward0>)

In [12]:
import torch.nn as nn

In [13]:
x=torch.eye(3)

In [18]:
nn.Linear(3,3)(x)

tensor([[-0.0332, -0.7392,  0.2024],
        [-0.0996, -0.7400, -0.2893],
        [-0.0119,  0.1433,  0.1907]], grad_fn=<AddmmBackward0>)